apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2p-downloads
  namespace: p2p
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
