apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: p2p
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
